services:
  - type: web
    name: vehicle-tracker
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: vehicle-tracker-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false

databases:
  - name: vehicle-tracker-db
    plan: basic-256mb
